name: rasa-extraction-dial
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - et_xmlfile=2.0.0=py312h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openpyxl=3.1.5=py312h5eee18b_1
  - openssl=3.0.18=hd6dcaed_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.11=h22baa00_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - annotated-types==0.7.0
      - anthropic==0.75.0
      - anyio==4.12.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - distro==1.9.0
      - docstring-parser==0.17.0
      - filetype==1.2.0
      - google-ai-generativelanguage==0.9.0
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - jiter==0.12.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - krippendorff==0.8.2
      - langchain==1.1.0
      - langchain-anthropic==1.2.0
      - langchain-core==1.1.0
      - langchain-google-genai==3.2.0
      - langchain-openai==1.1.0
      - langgraph==1.0.4
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.10
      - langsmith==0.4.49
      - numpy==2.3.5
      - openai==2.8.1
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - packaging==25.0
      - pandas==2.3.3
      - pip==24.3.1
      - proto-plus==1.26.1
      - protobuf==6.33.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rsa==4.9.1
      - six==1.17.0
      - sniffio==1.3.1
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.6.0
      - zstandard==0.25.0
prefix: /home/ksenia/miniconda3/envs/rasa-extraction-dial
